# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-15 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_managment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Заведение', 'verbose_name_plural': 'Заведения'},
        ),
    ]
