# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-16 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=1, max_length=250, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
